### ISSUE TITLE
Issue when compiling client templates

### ISSUE THREAD

**Issue by danmillar** [reshape/reshape#18]
When using `reshape?locals=false` to compile client templates, the reshape-expressions/lib/runtime.js is exported into the main.js without being passed through Babel first.

**Comment by jescalan** [comment]
Thanks for catching this! Fixed in `reshape-expression@0.1.2`, and included now in `reshape-standard@0.4.1`

**Comment by danmillar** [comment]
I'm still having issues compiling. It's now progressed past the declaration of the function due to your fix, but is complaining about the `let` declarations on line 9 and 10 of runtime.js. If I change these to `var` it compiles without issue. However, shouldn't the whole file be passed through Babel on compile to remove even the `const` etc. to be safe? like all the other JS project files are.

**Comment by jescalan** [comment]
Ah yeah good catch. So the runtime file is handled differently from client js files. I'll just be extra through this time 😁

**Comment by jescalan** [comment]
Ok published updates -- this time it should be fixed for real!

**Comment by danmillar** [comment]
Perfect, that's done it!
